spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost/stackoverdb}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 20
      idle-timeout: 10000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  flyway:
    locations: classpath:db/migration,classpath:db/datatest
