CREATE TABLE tag
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_activity_date TIMESTAMP WITHOUT TIME ZONE,
    has_synonyms       BOOLEAN,
    is_moderator_only  BOOLEAN,
    is_required        BOOLEAN,
    count              INTEGER,
    name               VARCHAR(255) NOT NULL,

    CONSTRAINT pk_tag PRIMARY KEY (id)
);